# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-30 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantDeliveryCourier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Create DateTime')),
                ('dateUpdated', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Create DateTime')),
                ('acceptedPacksFromPrivate', models.BooleanField(default=False)),
                ('acceptedPacksFromCompany', models.BooleanField(default=False)),
                ('enableNewRequests', models.BooleanField(default=True)),
                ('pickUpLocationCity', models.CharField(blank=True, default='', max_length=255)),
                ('pickUpLocationAddress', models.CharField(blank=True, default='', max_length=255)),
                ('pickUpLocationLat', models.FloatField(default=0.0)),
                ('pickUpLocationLng', models.FloatField(default=0.0)),
                ('priceRange10Km', models.FloatField(default=0.0)),
                ('enableRange10Km', models.BooleanField(default=False)),
                ('priceRange20Km', models.FloatField(default=0.0)),
                ('enableRange20Km', models.BooleanField(default=False)),
                ('priceRange50Km', models.FloatField(default=0.0)),
                ('enableRange50Km', models.BooleanField(default=False)),
                ('priceRangeMore50Km', models.FloatField(default=0.0)),
                ('enableRangeMore50Km', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='InstantDeliveryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Create DateTime')),
                ('dateUpdated', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Create DateTime')),
                ('sender', models.CharField(blank=True, default='', max_length=50)),
                ('locationFromCity', models.CharField(blank=True, default='', max_length=50)),
                ('locationFromAddress', models.CharField(blank=True, default='', max_length=255)),
                ('locationFromLat', models.FloatField(default=0.0)),
                ('locationFromLng', models.FloatField(default=0.0)),
                ('receiver', models.CharField(blank=True, default='', max_length=50)),
                ('locationToCity', models.CharField(blank=True, default='', max_length=50)),
                ('locationToAddress', models.CharField(blank=True, default='', max_length=255)),
                ('locationToLat', models.FloatField(default=0.0)),
                ('locationToLng', models.FloatField(default=0.0)),
                ('pickupFrom', models.TimeField(null=True)),
                ('pickupTo', models.TimeField(null=True)),
                ('deliveryFrom', models.TimeField(null=True)),
                ('deliveryTo', models.TimeField(null=True)),
                ('state', models.CharField(choices=[(b'NEW', b'NEW'), (b'NOT-QUORATE', b'NOT-QUORATE'), (b'ACCEPTED', b'ACCEPTED'), (b'CANCELLED', b'CANCELLED'), (b'TRANSIT', b'TRANSIT'), (b'TRANSIT-2', b'TRANSIT-2'), (b'DELIVERED', b'DELIVERED'), (b'NOT-DELIVERED', b'NOT-DELIVERED')], default=b'NEW', max_length=25)),
                ('isUrgent', models.BooleanField(default=False)),
                ('numberOfSmallBoxes', models.IntegerField(default=0)),
                ('numberOfMediumBoxes', models.IntegerField(default=0)),
                ('numberOfLargeBoxes', models.IntegerField(default=0)),
                ('priceRange', models.FloatField(default=0.0)),
                ('distance', models.FloatField(default=0.0)),
                ('notes', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('courierPIN', models.IntegerField(default=0)),
                ('collectPIN', models.IntegerField(default=0)),
                ('deliveryConfirmationPIN', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_buyer', to='core.Profile')),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instant_courier', to='core.Profile')),
            ],
            options={
                'verbose_name': 'Instant Delivery Order',
                'verbose_name_plural': 'Instant Delivery Orders',
            },
        ),
        migrations.CreateModel(
            name='InstantDeliveryOrderFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.FloatField(default=0)),
                ('text', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.InstantDeliveryOrder')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='InstantDeliveryOrderIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(choices=[(1, b'Against policy'), (2, b'Not corresponding'), (3, b'Not received'), (4, b'Other issue')])),
                ('description', models.TextField(default='', max_length=500)),
                ('state', models.CharField(choices=[(b'OPEN', b'OPEN'), (b'CLOSED', b'CLOSED')], default=b'OPEN', max_length=25)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chat')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.InstantDeliveryOrder')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
    ]
