import {
    MatAutocompleteModule,
    MatButtonModule,
    MatCardModule,
    MatCheckboxModule,
    MatDatepickerModule,
    MatDialogModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatSortModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatStepperModule,
    MatRadioModule,
    MatButtonToggleModule,
    MatTooltipModule,
    MatExpansionModule,
    MatChipsModule,
    MatProgressBarModule,
} from '@angular/material';
import {NgModule} from "@angular/core";
import { NgxMatSelectSearchModule } from 'ngx-mat-select-search';
import { MatBadgeModule } from '@angular/material/badge';


@NgModule({
    imports: [
        MatFormFieldModule,
        MatGridListModule,
        MatButtonModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatCardModule,
        MatSelectModule,
        MatDialogModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatMenuModule,
        MatTabsModule,
        MatIconModule,
        MatProgressSpinnerModule,
        MatTableModule,
        MatPaginatorModule,
        MatSortModule,
        MatSlideToggleModule,
        MatCheckboxModule,
        MatAutocompleteModule,
        MatStepperModule,
        MatRadioModule,
        MatButtonToggleModule,
        MatTooltipModule,
        MatExpansionModule,
        MatChipsModule,
        NgxMatSelectSearchModule,
        MatBadgeModule,
        MatProgressBarModule
    ],
    exports: [
        MatInputModule,
        MatFormFieldModule,
        MatButtonModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatSelectModule,
        MatCardModule,
        MatGridListModule,
        MatDialogModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatMenuModule,
        MatTabsModule,
        MatIconModule,
        MatProgressSpinnerModule,
        MatTableModule,
        MatPaginatorModule,
        MatSortModule,
        MatSlideToggleModule,
        MatCheckboxModule,
        MatAutocompleteModule,
        MatStepperModule,
        MatRadioModule,
        MatButtonToggleModule,
        MatTooltipModule,
        MatExpansionModule,
        MatChipsModule,
        NgxMatSelectSearchModule,
        MatBadgeModule,
        MatProgressBarModule
    ],
})
export class MaterialDesignModule {
}
