from django.conf.urls import url
from django.views.decorators.http import require_POST, require_http_methods, require_GET

from mobile import cronjobs
from mobile.views import orders, couriers, issues

mobileUrls = [
    url(
        r'^api/mobile/order/$',
        require_POST(orders.getOrders),
        name='get-orders'
    ),
    url(
        r'^api/mobile/order/home/$',
        require_POST(orders.getHomeOrders),
        name='get-home-orders'
    ),
    url(
        r'^api/mobile/order/(?P<order_id>\d+)$',
        require_GET(orders.getOrder),
        name='get-order'
    ),
    url(
        r'^api/mobile/order/courier/(?P<order_id>\d+)$',
        require_GET(orders.getCourierOrder),
        name='get-courier-order'
    ),
    url(
        r'^api/mobile/order/courier/new/(?P<order_id>\d+)$',
        require_GET(orders.getNewCourierOrder),
        name='get-courier-order'
    ),
    url(
        r'^api/mobile/order/create/$',
        require_POST(orders.createOrder),
        name='create-orders'
    ),
    url(
        r'^api/mobile/order/courier/$',
        require_POST(orders.getCourierOrders),
        name='get-courier-orders'
    ),
    url(
        r'^api/mobile/order/courier/home/$',
        require_POST(orders.getCourierHomeOrders),
        name='get-home-courier-orders'
    ),
    url(
        r'^api/mobile/order/accept/(?P<order_id>\d+)$',
        require_POST(orders.acceptOrder),
        name='accept-order'
    ),
    url(
        r'^api/mobile/order/collect/(?P<order_id>\d+)$',
        require_POST(orders.collectOrder),
        name='collect-order'
    ),
    url(
        r'^api/mobile/order/deliver/(?P<order_id>\d+)$',
        require_POST(orders.deliverOrder),
        name='deliver-order'
    ),
    url(
        r'^api/mobile/order/transit2/(?P<order_id>\d+)$',
        require_POST(orders.secondTransitOrder),
        name='second-transit-order'
    ),
    url(
        r'^api/mobile/order/notDelivered/(?P<order_id>\d+)$',
        require_POST(orders.orderNotDelivered),
        name='not-delivered-order'
    ),
    url(
        r'^api/mobile/order/feedback/(?P<order_id>\d+)$',
        require_POST(orders.sendFeedbackOrder),
        name='send-feedback-orders'
    ),
    url(
        r'^api/mobile/courier/create/$',
        couriers.createCourier,
        name='create-courier'
    ),
    url(
        r'^api/mobile/courier/edit/$',
        require_http_methods(['PUT'])(couriers.editCourier),
        name='edit-courier'
    ),
    url(
        r'^api/mobile/courier/(?P<courier_id>\d+)$',
        require_http_methods(['GET'])(couriers.getCourier),
        name='get-courier'
    ),
    url(
        r'^api/mobile/courier/profile/$',
        require_http_methods(['GET'])(couriers.getCourierByProfile),
        name='get-courier-by-profile'
    ),
    url(
        r'^api/mobile/courier/toggleEnableNewRequests/$',
        require_http_methods(['POST'])(couriers.toggleEnableNewRequests),
        name='courier-toggle-enable-new-requests'
    ),
    url(
        r'^api/mobile/courier/search/$',
        require_http_methods(['POST'])(couriers.searchCourier),
        name='search-couriers'
    ),
    url(
        r'^api/mobile/courier/requests/$',
        require_http_methods(['POST'])(couriers.searchCourierOrderRequests),
        name='search-couriers-order-requests'
    ),
    url(
        r'^cronjobs/processExpiredInstantDeliveryOrders/$',
        cronjobs.processExpiredInstantDeliveryOrders,
        name='process-expired-instant-delivery-orders'
    ),
    url(
        r'^api/mobile/issue/(?P<orderId>\d+)$',
        require_http_methods(['GET'])(issues.getIssue),
        name='get-issue'
    ),
    url(
        r'^api/mobile/issue/createIssueChatMessage/$',
        issues.createIssueChatMessage,
        name='create-issue-chat-message'
    ),
]
