# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedBetaEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetterEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='partnercourier',
            options={'verbose_name': 'Partner Courier', 'verbose_name_plural': 'Partner Couriers'},
        ),
        migrations.AlterModelOptions(
            name='partnercourierdestinationzone',
            options={'verbose_name': 'Partner Courier Zone Standard', 'verbose_name_plural': 'Partner Courier Zones Standard'},
        ),
        migrations.AlterModelOptions(
            name='partnercourierorigindestinationzone',
            options={'verbose_name': 'Partner Courier Zone Express', 'verbose_name_plural': 'Partner Courier Zones Express'},
        ),
        migrations.AddField(
            model_name='order',
            name='buyGoodsFrom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[(b'USD', b'Dollar'), (b'EUR', b'Euro')], default=b'USD', max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryAddress',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='goodValue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='parcelSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='parcelWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='currencySetting',
            field=models.CharField(choices=[(b'USD', b'Dollar'), (b'EUR', b'Euro')], default=b'USD', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='languageSetting',
            field=models.CharField(choices=[(b'english', b'English')], default=b'english', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='measuresSetting',
            field=models.CharField(choices=[(b'metric', b'Metric'), (b'imperial', b'Imperial')], default=b'metric', max_length=40),
        ),
        migrations.AlterField(
            model_name='partnercourierprice',
            name='weight',
            field=models.FloatField(default='0.0'),
        ),
    ]
