# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-20 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180612_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languageSetting',
            field=models.CharField(choices=[(b'en', b'English')], default=b'en', max_length=40),
        ),
    ]
