# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180620_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deliveryAddress',
            field=models.CharField(default='', max_length=255),
        ),
    ]
