# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_profileaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='profileAddress',
            new_name='profileForwarderAddress',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='profileAddress',
            new_name='profileForwarderAddress',
        ),
    ]
