"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import platform

# PRODUCTION
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEFAULT_AVATAR_IMAGE_PATH = os.path.join(BASE_DIR, 'server/adminmedia/images/default_avatar.png')

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-custom-authorization'
)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'captcha',
    'corsheaders',
    'core',
    'transactions',
    'mobile',
    'debugapp',
    'fixture_magic',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.XMirrorTokenAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_PERMISSION_CLASSES': [
    ],
    'PAGE_SIZE': 10
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debugapp.middleware.ExceptionLog'
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'server/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'context_processors.global_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'

TRANSACTION_STATUS = (
    ('NEW', 'NEW'),
    ('PENDING', 'PENDING'),
    ('ABORTED', 'ABORTED'),
    ('COMPLETED', 'COMPLETED'),
    ('HOLDING', 'HOLDING')
)

TRANSACTION_TYPES = (
    ('PAYMENT', 'PAYMENT'),
    ('WITHDRAW', 'WITHDRAW'),
    ('REFUND', 'REFUND'),
    ('ADMIN', 'ADMIN'),
    ('2FASMS', '2FASMS'),
)

ORDER_STATUS_CHOICES = (
    ('NEW', 'NEW'),
    ('PAID', 'PAID'),
    ('CANCELLED', 'CANCELLED'),
    ('ACCEPTED', 'ACCEPTED'),
    ('REFUSED', 'REFUSED'),
    ('DELIVERED', 'DELIVERED'),
    ('FORWARDED', 'FORWARDED'),
    ('COLLECTING', 'COLLECTING'),
    ('RECEIVED', 'RECEIVED'),
)

ORDER_STATUS = {
    'new': 'NEW',
    'cancelled': 'CANCELLED',
    'paid': 'PAID',
    'refused': 'REFUSED',
    'accepted': 'ACCEPTED',
    'collecting': 'COLLECTING',
    'forwarded': 'FORWARDED',
    'delivered': 'DELIVERED',
    'received': 'RECEIVED',
}

ORDER_INSTANT_DELIVERY_STATUS = {
    'new': 'NEW',
    'not-quorate': 'NOT-QUORATE',
    'accepted': 'ACCEPTED',
    'cancelled': 'CANCELLED',
    'transit': 'TRANSIT',
    'transit-2': 'TRANSIT-2',
    'delivered': 'DELIVERED',
    'not-delivered': 'NOT-DELIVERED',
}

ORDER_INSTANT_DELIVERY_STATUS_CHOICES = (
    ('NEW', 'NEW'),
    ('NOT-QUORATE', 'NOT-QUORATE'),
    ('ACCEPTED', 'ACCEPTED'),
    ('CANCELLED', 'CANCELLED'),
    ('TRANSIT', 'TRANSIT'),
    ('TRANSIT-2', 'TRANSIT-2'),
    ('DELIVERED', 'DELIVERED'),
    ('NOT-DELIVERED', 'NOT-DELIVERED'),
)

COURIER_TYPES_CHOICES = (
    ('COURIER01', 'DHL'),
    ('COURIER02', 'UPS'),
    ('COURIER03', 'FedEx'),
    ('COURIERCUSTOM', 'Other'),  # Never change tuple first value on this one!!!
)

ORDER_TRACKING_INFO_STATUS_CHOICES = (
    ('1', 'First'),
    ('2', 'Second'),
    ('3', 'Third'),
)

SERVICE_TYPES = (
    ("p2p-freight", "P2P Freight Forwarding"),
    ("package-collecting", "Package Collecting"),
    ("express-delivery", "Express Delivery"),
)

SERVICE_PRICE_TYPES = (
    ("cheap", "Cheap"),
    ("standard", "Standard"),
    ("express", "Express"),
)

PROFILE_LANGUAGE_SETTINGS = (
    ("en", "English"),
)

PROFILE_CURRENCY_SETTINGS = (
    ("USD", "Dollar"),
    ("EUR", "Euro"),
)

PROFILE_MEASURE_SETTINGS = (
    ("metric", "Metric"),
    ("imperial", "Imperial"),
)

DEFAULT_FORWARDER_PARTNER_NAME = "DHL"

ISSUE_STATUS_CHOICES = (
    ('OPEN', 'OPEN'),
    ('CLOSED', 'CLOSED'),
)

ISSUE_STATUS = {
    'OPEN': 'OPEN',
    'CLOSED': 'CLOSED'
}

ISSUE_TYPES = {
    1: 'Against policy',
    2: 'Not corresponding',
    3: 'Not received',
    4: 'Other issue'
}

ISSUE_TYPES_CHOICES = (
    (1, 'Against policy'),
    (2, 'Not corresponding'),
    (3, 'Not received'),
    (4, 'Other issue')
)

CONFIGURATION_PARAMETERS = {  # key always lowercase | value int|float/string
    'p2p_forwarding_cheap_eta': 0,
    'p2p_forwarding_standard_eta': 0,
    'p2p_forwarding_express_eta': 0,
    'forwarding_fee_percentage_level_1': 0,
    'btc_deposit_percentage': 0,
    'lwf_deposit_percentage': 0,
    'paypal_deposit_percentage': 0,
    'dhl_partner_fee': 0,
    'courier_partner_vat_percentage': 0,
    'courier_partner_duty_percentage': 0,
    'courier_partner_gas_percentage': 0,
    'courier_partner_vat_percentage_3C': 0,
    'p2p_forwarder_maxgoodvalue_percentage': 0,
    'instant_delivery_order_minutes_expire': 0,
    'max_order_notes': 10,
    'enable_closed_signup_list': False,
    'mobileapp_enabled': True
}

TWO_FACTOR_SMS_COST = 1

MANAGERS_GROUP_NAME = 'managers'

ONESIGNAL_REST_API_KEY = 'PUTHERE'
ONESIGNAL_APP_ID = 'PUTHERE'

MOBILE_ORDER_PIN_DIGITS = 4

CURRENCY_API_URL = 'https://api.coinmarketcap.com/v2/ticker/?convert=EUR'
LWF_CURRENCY_API_URL = 'https://api.coinmarketcap.com/v2/ticker/2761/?convert=EUR'

MAX_IMAGE_SIZE_UPLOAD = 6291456 #Bytes

RECAPTCHA_PUBLIC_KEY = 'PUTHERE'
RECAPTCHA_PRIVATE_KEY = 'PUTHERE'
GOOGLE_API_KEY = 'PUTHERE'

TRANSACTION_PROCESS_RESTART_TIMEOUT = 1800 #seconds
PROFILE_ACTIVATION_KEY_EXPIRE_TIMEOUT = 1 #hours

if platform.node() == 'lwf.global' or platform.node() == 'lwf':

    REST_FRAMEWORK_CUSTOM_PATH = 'rest'
    REST_FRAMEWORK_ADMIN_SECRET_KEY = '7942c7a4-6e50-4950-8cbe-b35325f07087'

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = '+&zzr$i^0nhr^bat$c3_u+19)@c1&pad4%a5htd(+!g$cx^!$#'

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = False
    DEBUG_LOG_EXCEPTIONS = True

    ALLOWED_HOSTS = ['lwf.global']

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'lwf',
            'USER': 'dbuser',
            'PASSWORD': 'PUTHERE',
            'HOST': 'localhost'
        }
    }

    # Password validation
    # https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/1.11/topics/i18n/

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'UTC'

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.11/howto/static-files/

    STATIC_URL = '/static/'
    STATIC_ROOT = '/home/lwf/static/'

    MEDIA_URL = '/media/'
    MEDIA_ROOT = '/home/lwf/media/'

    FRONTEND_HOST = 'lwf.global'
    FRONTEND_PORT = '80'
    FRONTEND_WEBAPP_NAME = ''
    FRONTEND_SSL = False
    BACKEND_HOST = FRONTEND_HOST
    BACKEND_PORT = '443'
    BACKEND_SSL = True

    EMAIL_DEFAULT_FROM = 'PUTHERE'
    EMAIL_FROM = 'PUTHERE'
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_USE_TLS = False
    EMAIL_HOST = 'PUTHERE'
    EMAIL_PORT = 25
    EMAIL_HOST_USER = 'PUTHERE'
    EMAIL_HOST_PASSWORD = 'PUTHERE'

    SMS_API_SID = 'PUTHERE'
    SMS_API_TOKEN = 'PUTHERE'
    SMS_FROM_NUMBER = 'PUTHERE'
    SMS_SERVICE_SID = 'PUTHERE'

    BTC_URL_ADDRESS_TRANSACTIONS = 'https://api.blockcypher.com/v1/btc/main/addrs/ADDRESS?token=a5426d31537f4434ac1319c0b324f36f'
    ETH_URL_ADDRESS_TRANSACTIONS = 'https://api.etherscan.io/api?module=account&action=txlist&address=ADDRESS&apikey=FIXRKK8K58XUWWXC7ATX1IXASZU5QY5D8G'
    LWF_URL_ADDRESS_TRANSACTIONS = 'https://explorer.lwf.io/api/transactions/getTransactionsByAddress?address=ADDRESS'

    PAYPAL_PAYMENT_DETAILS_ENDPOINT = "https://api.live.paypal.com/v1/payments/payment/%s"
    PAYPAL_GET_AUTH_TOKEN_ENDPOINT = "https://api.live.paypal.com/v1/oauth2/token?grant_type=client_credentials"
    PAYPAL_BUSINESS_ACCOUNT_EMAIL = "PUTHERE"
    PAYPAL_MERCHANT_ID = "PUTHERE"
    PAYPAL_SECRET = "PUTHERE"

else:
    # DEV

    REST_FRAMEWORK_CUSTOM_PATH = ''
    REST_FRAMEWORK_ADMIN_SECRET_KEY = '7942c7a4-6e50-4950-8cbe-b35325f07087'

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = '+&zzr$i^0nhr^bat$c3_u+19)@c1&pad4%a5htd(+!g$cx^!$#'

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True
    DEBUG_LOG_EXCEPTIONS = True

    ALLOWED_HOSTS = ['*']

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'lwf',
            'USER': 'lwf',
            'PASSWORD': 'lwf',
            'HOST': 'localhost'
        }
    }

    # Password validation
    # https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [

    ]

    # Internationalization
    # https://docs.djangoproject.com/en/1.11/topics/i18n/

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'UTC'

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.11/howto/static-files/

    STATIC_URL = '/static/'
    STATIC_ROOT = 'static/'

    MEDIA_URL = '/media/'
    MEDIA_ROOT = 'media/'

    MEDIA_URL = '/media/'

    FRONTEND_HOST = 'localhost'
    FRONTEND_PORT = '4200'
    FRONTEND_WEBAPP_NAME = ''
    FRONTEND_SSL = False
    BACKEND_HOST = FRONTEND_HOST
    BACKEND_PORT = '8000'
    BACKEND_SSL = False

    EMAIL_DEFAULT_FROM = 'PUTHERE'
    EMAIL_FROM = 'PUTHERE'
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_USE_TLS = False
    EMAIL_HOST = 'PUTHERE'
    EMAIL_PORT = 25
    EMAIL_HOST_USER = 'PUTHERE'
    EMAIL_HOST_PASSWORD = 'PUTHERE'

    SMS_API_SID = 'PUTHERE'
    SMS_API_TOKEN = 'PUTHERE'
    SMS_FROM_NUMBER = 'PUTHERE'
    SMS_SERVICE_SID = 'PUTHERE'

    BTC_URL_ADDRESS_TRANSACTIONS = 'https://api.blockcypher.com/v1/btc/main/addrs/ADDRESS?token=a5426d31537f4434ac1319c0b324f36f'
    ETH_URL_ADDRESS_TRANSACTIONS = 'https://api.etherscan.io/api?module=account&action=txlist&address=ADDRESS&apikey=FIXRKK8K58XUWWXC7ATX1IXASZU5QY5D8G'
    LWF_URL_ADDRESS_TRANSACTIONS = 'https://explorer.lwf.io/api/transactions/getTransactionsByAddress?address=ADDRESS'

    PAYPAL_PAYMENT_DETAILS_ENDPOINT = "https://api.sandbox.paypal.com/v1/payments/payment/%s"
    PAYPAL_GET_AUTH_TOKEN_ENDPOINT = "https://api.sandbox.paypal.com/v1/oauth2/token?grant_type=client_credentials"
    PAYPAL_BUSINESS_ACCOUNT_EMAIL = "PUTHERE"
    PAYPAL_MERCHANT_ID = "PUTHERE"
    PAYPAL_SECRET = "PUTHERE"
