# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-20 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20180620_1312'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed', models.BooleanField(default=False)),
                ('hash', models.CharField(default=transactions.models.uniqueUuid, editable=False, max_length=255, unique=True)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Notification')),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='transactions.WithdrawTransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdraw request',
                'verbose_name_plural': 'Withdraw requests',
            },
        ),
    ]
