# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-22 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_withdrawrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='requestedAmount',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='requestedCcAddress',
            field=models.CharField(default=1, editable=False, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='requestedCurrency',
            field=models.CharField(default=1, editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='transaction',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.WithdrawTransaction'),
        ),
    ]
