# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-25 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20180622_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dollarEuroRate',
            field=models.FloatField(default=0.0),
        ),
    ]
