# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-25 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_dollareurorate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='dollarEuroRate',
            new_name='freezedEur',
        ),
        migrations.AddField(
            model_name='transaction',
            name='freezedUsd',
            field=models.FloatField(default=0.0),
        ),
    ]
