# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-22 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_lwftransaction_receiptsequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lwftransaction',
            name='receiptSequence',
        ),
    ]
