# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-06 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_lwftransaction_receiptsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='lwftransaction',
            name='receiptSequence',
            field=models.CharField(default=transactions.models.uniqueUuid, editable=False, max_length=254, unique=True),
        ),
    ]
