# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_lwftransaction_receiptsequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instantdeliverypaymenttransaction',
            options={'verbose_name': 'Instant delivery order payment transaction', 'verbose_name_plural': 'Instant delivery order payment transactions'},
        ),
        migrations.AlterModelOptions(
            name='lwftransaction',
            options={'verbose_name': 'Internal Transaction', 'verbose_name_plural': 'Internal Transactions'},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'verbose_name': 'Order payment transaction', 'verbose_name_plural': 'Order payment transactions'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactioncaution',
            options={'verbose_name': 'Caution deposit transaction', 'verbose_name_plural': 'Caution deposit transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactionpaypal',
            options={'verbose_name': 'Paypal deposit transaction', 'verbose_name_plural': 'Paypal deposit transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactionsprocess',
            options={'verbose_name': 'Crypto currency transaction process', 'verbose_name_plural': 'Crypto currency transaction processes'},
        ),
        migrations.AlterField(
            model_name='lwftransaction',
            name='amount',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='lwftransaction',
            name='feeAmount',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='lwftransaction',
            name='feePercentage',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='lwfwallet',
            name='credit',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='feeAmount',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='feePercentage',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='freezedEur',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='freezedUsd',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='transactioncaution',
            name='amount',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='cost',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='transactionpaypal',
            name='paymentId',
            field=models.CharField(default=b'', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='credit',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='deposit',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
