# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20180927_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawtransaction',
            name='transactionId',
            field=models.CharField(default=b'', editable=False, max_length=255),
        ),
    ]
