from django.conf.urls import url

from transactions import cronjobs, wallets
from transactions.views import views, payments, adminviews

transactionUrls = [
    url(
        r'^api/wallet/transactions/deposit/$',
        wallets.getDepositTransactions,
        name='get-deposit-transactions'
    ),
    url(
        r'^api/wallet/transactions/deposit/paypal/$',
        wallets.getDepositPayPalTransactions,
        name='get-deposit-paypal-transactions'
    ),
    url(
        r'^api/wallet/transactions/withdraw/$',
        wallets.getWithdrawTransactions,
        name='get-withdraw-transactions'
    ),
    url(
        r'^api/wallet/getAddress/$',
        wallets.getAddress,
        name='get-address'
    ),
    url(
        r'^api/wallet/deposit/$',
        wallets.deposit,
        name='deposit-caution'
    ),
    url(
        r'^api/wallet/deposit/paypal/$',
        wallets.depositPaypal,
        name='deposit-paypal'),
    url(
        r'^api/wallet/deposit/invoice/(?P<transaction_id>\d+)$',
        views.getDepositReceiptPdf,
        name='deposit-receipt'
    ),
    url(
        r'^api/wallet/withdraw/invoice/(?P<transaction_id>\d+)$',
        views.getWithdrawReceiptPdf,
        name='withdraw-receipt'
    ),
    url(
        r'^api/wallet/deposit/paypal/invoice/(?P<transaction_id>\d+)$',
        views.getDepositPaypalReceiptPdf,
        name='deposit-paypal-receipt'
    ),
    url(
        r'^api/wallet/order/buyer/report/(?P<order_id>\d+)$',
        views.getBuyerOrderPaymentReportPdf,
        name='order-buyer-payment-report'
    ),
    url(
        r'^api/wallet/order/forwarder/report/(?P<order_id>\d+)$',
        views.getForwarderOrderPaymentReportPdf,
        name='order-forwarder-payment-report'
    ),
    url(
        r'^api/wallet/withdraw/$',
        wallets.withdraw,
        name='withdraw'
    ),
    url(
        r'^api/auth/withdrawConfirm/$',
        wallets.withdrawConfirm,
        name='withdrawConfirm'
    ),
    url(
        r'^api/transaction/setAsPaidWithdrawRequest/$',
        views.setAsPaidWithdrawRequest,
        name='set-as-paid-withdraw-request'
    ),
    url(
        r'^api/transaction/forceCompletePaymentTransaction/$',
        views.forceCompletePaymentTransaction,
        name='force-complete-payment-transaction'
    ),
    url(
        r'^api/transaction/forceCompleteInstantDeliveryPaymentTransaction/$',
        views.forceCompleteInstantDeliveryPaymentTransaction,
        name='force-complete-instant-delivery-payment-transaction'
    ),
    url(
        r'^api/order/payment/$',
        payments.orderPayment,
        name='order-payment'
    ),
    url(
        r'^admin/catch_user_bc.html',
        adminviews.adminCatchUserBc,
        name='admin-catch-user-bc'
    ),
    url(
        r'^admin/send_user_bc.html',
        adminviews.adminSendUserBc,
        name='admin-send-user-bc'
    ),
    url(
        r'^cronjobs/processTransactions/$',
        cronjobs.processTransactions,
        name='process-transactions'
    ),
    url(
        r'^cronjobs/processNotifications/$',
        cronjobs.processNotifications,
        name='process-notifications'
    ),
    url(
        r'^cronjobs/processCurrencies/$',
        cronjobs.processCurrencies,
        name='process-currencies'
    ),
]
